chmod 755 -R /var/www/html/modules/agent_console
chmod 755 -R /var/www/html/modules/hispana_agendados_agente
chmod 755 -R /var/www/html/modules/hispana_base_clientes
chmod 755 -R /var/www/html/modules/hispana_base_lista
chmod 755 -R /var/www/html/modules/hispana_base_recarga
chmod 755 -R /var/www/html/modules/hispana_bases_eliminacion
chmod 755 -R /var/www/html/modules/hispana_breaks
chmod 755 -R /var/www/html/modules/hispana_call_types
chmod 755 -R /var/www/html/modules/hispana_campania_derivada
chmod 755 -R /var/www/html/modules/hispana_campania_recargable
chmod 755 -R /var/www/html/modules/hispana_campania_regestion
chmod 755 -R /var/www/html/modules/hispana_clientes_agendados
chmod 755 -R /var/www/html/modules/hispana_clientes_campania
chmod 755 -R /var/www/html/modules/hispana_clientes_campania_r
chmod 755 -R /var/www/html/modules/hispana_clientes_datosbasicos
chmod 755 -R /var/www/html/modules/hispana_clientes_datosotrosform
chmod 755 -R /var/www/html/modules/hispana_clientes_datosotros_reporte
chmod 755 -R /var/www/html/modules/hispana_clientes_manuales
chmod 755 -R /var/www/html/modules/hispana_crear_campania
chmod 755 -R /var/www/html/modules/hispana_form_designer
chmod 755 -R /var/www/html/modules/hispana_form_list
chmod 755 -R /var/www/html/modules/hispana_interfaz_agente
chmod 755 -R /var/www/html/modules/hispana_listado_call_types
chmod 755 -R /var/www/html/modules/hispana_listado_campanias
chmod 755 -R /var/www/html/modules/hispana_listado_recarga
chmod 755 -R /var/www/html/modules/hispana_listado_reporte_offline
chmod 755 -R /var/www/html/modules/hispana_logger
chmod 755 -R /var/www/html/modules/hispana_reporte_break_agente
chmod 755 -R /var/www/html/modules/hispana_reporte_breaks
chmod 755 -R /var/www/html/modules/hispana_reporte_calltype
chmod 755 -R /var/www/html/modules/hispana_reporte_campania_audio
chmod 755 -R /var/www/html/modules/hispana_reporte_campania_detalle
chmod 755 -R /var/www/html/modules/hispana_reporte_campania_recargable
chmod 755 -R /var/www/html/modules/hispana_reporte_efectividad
chmod 755 -R /var/www/html/modules/hispana_reporte_efectividad_recargable
chmod 755 -R /var/www/html/modules/hispana_reporte_ultima_gestion
chmod 755 -R /var/www/html/modules/hispana_reporte_ultima_gestion_recargable
chmod 755 -R /var/www/html/modules/hispana_telefonos_inactivos

chown asterisk:asterisk -R /var/www/html/modules/agent_console
chown asterisk:asterisk -R /var/www/html/modules/hispana_agendados_agente
chown asterisk:asterisk -R /var/www/html/modules/hispana_base_clientes
chown asterisk:asterisk -R /var/www/html/modules/hispana_base_lista
chown asterisk:asterisk -R /var/www/html/modules/hispana_base_recarga
chown asterisk:asterisk -R /var/www/html/modules/hispana_bases_eliminacion
chown asterisk:asterisk -R /var/www/html/modules/hispana_breaks
chown asterisk:asterisk -R /var/www/html/modules/hispana_call_types
chown asterisk:asterisk -R /var/www/html/modules/hispana_campania_derivada
chown asterisk:asterisk -R /var/www/html/modules/hispana_campania_recargable
chown asterisk:asterisk -R /var/www/html/modules/hispana_campania_regestion
chown asterisk:asterisk -R /var/www/html/modules/hispana_clientes_agendados
chown asterisk:asterisk -R /var/www/html/modules/hispana_clientes_campania
chown asterisk:asterisk -R /var/www/html/modules/hispana_clientes_campania_r
chown asterisk:asterisk -R /var/www/html/modules/hispana_clientes_datosbasicos
chown asterisk:asterisk -R /var/www/html/modules/hispana_clientes_datosotrosform
chown asterisk:asterisk -R /var/www/html/modules/hispana_clientes_datosotros_reporte
chown asterisk:asterisk -R /var/www/html/modules/hispana_clientes_manuales
chown asterisk:asterisk -R /var/www/html/modules/hispana_crear_campania
chown asterisk:asterisk -R /var/www/html/modules/hispana_form_designer
chown asterisk:asterisk -R /var/www/html/modules/hispana_form_list
chown asterisk:asterisk -R /var/www/html/modules/hispana_interfaz_agente
chown asterisk:asterisk -R /var/www/html/modules/hispana_listado_call_types
chown asterisk:asterisk -R /var/www/html/modules/hispana_listado_campanias
chown asterisk:asterisk -R /var/www/html/modules/hispana_listado_recarga
chown asterisk:asterisk -R /var/www/html/modules/hispana_listado_reporte_offline
chown asterisk:asterisk -R /var/www/html/modules/hispana_logger
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_break_agente
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_breaks
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_calltype
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_campania_audio
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_campania_detalle
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_campania_recargable
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_efectividad
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_efectividad_recargable
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_ultima_gestion
chown asterisk:asterisk -R /var/www/html/modules/hispana_reporte_ultima_gestion_recargable
chown asterisk:asterisk -R /var/www/html/modules/hispana_telefonos_inactivos

